### ISSUE TITLE
moma_cup_log.json needs Unloaded Date & Unloaded By

### ISSUE THREAD

**Issue by jobrie12** [nickdobson/xina-init#1]
See title, but Unloaded Date and Unloaded By fields for MOMA Cup Log, could put in XINA2 and 3

**Comment by nickdobson** [comment]
Done in 2, still need to update 3.

**Comment by jobrie12** [comment]
So these additions aren't reflected in xina-init?

**Comment by nickdobson** [comment]
No I need to commit a lot of changes, it got a bit messy with recent updates, I'll sort it out by the end of the day.

**Comment by jobrie12** [comment]
Ah perfect, thanks!
